#include <GL/gl.h>
#include <GL/glx.h>

// GL_VERSION_1_0

extern void (*next_glAccum)(GLenum op, GLfloat value);
extern void (*next_glAlphaFunc)(GLenum func, GLfloat ref);
extern void (*next_glBegin)(GLenum mode);
extern void (*next_glBitmap)(GLsizei width, GLsizei height, GLfloat xorig, GLfloat yorig, GLfloat xmove, GLfloat ymove, const GLubyte* bitmap);
extern void (*next_glBlendFunc)(GLenum sfactor, GLenum dfactor);
extern void (*next_glCallList)(GLuint list);
extern void (*next_glCallLists)(GLsizei n, GLenum type, const void * lists);
extern void (*next_glClear)(GLbitfield mask);
extern void (*next_glClearAccum)(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
extern void (*next_glClearColor)(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
extern void (*next_glClearDepth)(GLdouble depth);
extern void (*next_glClearIndex)(GLfloat c);
extern void (*next_glClearStencil)(GLint s);
extern void (*next_glClipPlane)(GLenum plane, const GLdouble* equation);
extern void (*next_glColor3b)(GLbyte red, GLbyte green, GLbyte blue);
extern void (*next_glColor3bv)(const GLbyte* v);
extern void (*next_glColor3d)(GLdouble red, GLdouble green, GLdouble blue);
extern void (*next_glColor3dv)(const GLdouble* v);
extern void (*next_glColor3f)(GLfloat red, GLfloat green, GLfloat blue);
extern void (*next_glColor3fv)(const GLfloat* v);
extern void (*next_glColor3i)(GLint red, GLint green, GLint blue);
extern void (*next_glColor3iv)(const GLint* v);
extern void (*next_glColor3s)(GLshort red, GLshort green, GLshort blue);
extern void (*next_glColor3sv)(const GLshort* v);
extern void (*next_glColor3ub)(GLubyte red, GLubyte green, GLubyte blue);
extern void (*next_glColor3ubv)(const GLubyte* v);
extern void (*next_glColor3ui)(GLuint red, GLuint green, GLuint blue);
extern void (*next_glColor3uiv)(const GLuint* v);
extern void (*next_glColor3us)(GLushort red, GLushort green, GLushort blue);
extern void (*next_glColor3usv)(const GLushort* v);
extern void (*next_glColor4b)(GLbyte red, GLbyte green, GLbyte blue, GLbyte alpha);
extern void (*next_glColor4bv)(const GLbyte* v);
extern void (*next_glColor4d)(GLdouble red, GLdouble green, GLdouble blue, GLdouble alpha);
extern void (*next_glColor4dv)(const GLdouble* v);
extern void (*next_glColor4f)(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
extern void (*next_glColor4fv)(const GLfloat* v);
extern void (*next_glColor4i)(GLint red, GLint green, GLint blue, GLint alpha);
extern void (*next_glColor4iv)(const GLint* v);
extern void (*next_glColor4s)(GLshort red, GLshort green, GLshort blue, GLshort alpha);
extern void (*next_glColor4sv)(const GLshort* v);
extern void (*next_glColor4ub)(GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha);
extern void (*next_glColor4ubv)(const GLubyte* v);
extern void (*next_glColor4ui)(GLuint red, GLuint green, GLuint blue, GLuint alpha);
extern void (*next_glColor4uiv)(const GLuint* v);
extern void (*next_glColor4us)(GLushort red, GLushort green, GLushort blue, GLushort alpha);
extern void (*next_glColor4usv)(const GLushort* v);
extern void (*next_glColorMask)(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha);
extern void (*next_glColorMaterial)(GLenum face, GLenum mode);
extern void (*next_glCopyPixels)(GLint x, GLint y, GLsizei width, GLsizei height, GLenum type);
extern void (*next_glCullFace)(GLenum mode);
extern void (*next_glDeleteLists)(GLuint list, GLsizei range);
extern void (*next_glDepthFunc)(GLenum func);
extern void (*next_glDepthMask)(GLboolean flag);
extern void (*next_glDepthRange)(GLdouble near, GLdouble far);
extern void (*next_glDisable)(GLenum cap);
extern void (*next_glDrawBuffer)(GLenum buf);
extern void (*next_glDrawPixels)(GLsizei width, GLsizei height, GLenum format, GLenum type, const void * pixels);
extern void (*next_glEdgeFlag)(GLboolean flag);
extern void (*next_glEdgeFlagv)(const GLboolean* flag);
extern void (*next_glEnable)(GLenum cap);
extern void (*next_glEnd)();
extern void (*next_glEndList)();
extern void (*next_glEvalCoord1d)(GLdouble u);
extern void (*next_glEvalCoord1dv)(const GLdouble* u);
extern void (*next_glEvalCoord1f)(GLfloat u);
extern void (*next_glEvalCoord1fv)(const GLfloat* u);
extern void (*next_glEvalCoord2d)(GLdouble u, GLdouble v);
extern void (*next_glEvalCoord2dv)(const GLdouble* u);
extern void (*next_glEvalCoord2f)(GLfloat u, GLfloat v);
extern void (*next_glEvalCoord2fv)(const GLfloat* u);
extern void (*next_glEvalMesh1)(GLenum mode, GLint i1, GLint i2);
extern void (*next_glEvalMesh2)(GLenum mode, GLint i1, GLint i2, GLint j1, GLint j2);
extern void (*next_glEvalPoint1)(GLint i);
extern void (*next_glEvalPoint2)(GLint i, GLint j);
extern void (*next_glFeedbackBuffer)(GLsizei size, GLenum type, GLfloat* buffer);
extern void (*next_glFinish)();
extern void (*next_glFlush)();
extern void (*next_glFogf)(GLenum pname, GLfloat param);
extern void (*next_glFogfv)(GLenum pname, const GLfloat* params);
extern void (*next_glFogi)(GLenum pname, GLint param);
extern void (*next_glFogiv)(GLenum pname, const GLint* params);
extern void (*next_glFrontFace)(GLenum mode);
extern void (*next_glFrustum)(GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar);
extern GLuint (*next_glGenLists)(GLsizei range);
extern void (*next_glGetBooleanv)(GLenum pname, GLboolean* data);
extern void (*next_glGetClipPlane)(GLenum plane, GLdouble* equation);
extern void (*next_glGetDoublev)(GLenum pname, GLdouble* data);
extern GLenum (*next_glGetError)();
extern void (*next_glGetFloatv)(GLenum pname, GLfloat* data);
extern void (*next_glGetIntegerv)(GLenum pname, GLint* data);
extern void (*next_glGetLightfv)(GLenum light, GLenum pname, GLfloat* params);
extern void (*next_glGetLightiv)(GLenum light, GLenum pname, GLint* params);
extern void (*next_glGetMapdv)(GLenum target, GLenum query, GLdouble* v);
extern void (*next_glGetMapfv)(GLenum target, GLenum query, GLfloat* v);
extern void (*next_glGetMapiv)(GLenum target, GLenum query, GLint* v);
extern void (*next_glGetMaterialfv)(GLenum face, GLenum pname, GLfloat* params);
extern void (*next_glGetMaterialiv)(GLenum face, GLenum pname, GLint* params);
extern void (*next_glGetPixelMapfv)(GLenum map, GLfloat* values);
extern void (*next_glGetPixelMapuiv)(GLenum map, GLuint* values);
extern void (*next_glGetPixelMapusv)(GLenum map, GLushort* values);
extern void (*next_glGetPolygonStipple)(GLubyte* mask);
extern const GLubyte* (*next_glGetString)(GLenum name);
extern void (*next_glGetTexEnvfv)(GLenum target, GLenum pname, GLfloat* params);
extern void (*next_glGetTexEnviv)(GLenum target, GLenum pname, GLint* params);
extern void (*next_glGetTexGendv)(GLenum coord, GLenum pname, GLdouble* params);
extern void (*next_glGetTexGenfv)(GLenum coord, GLenum pname, GLfloat* params);
extern void (*next_glGetTexGeniv)(GLenum coord, GLenum pname, GLint* params);
extern void (*next_glGetTexImage)(GLenum target, GLint level, GLenum format, GLenum type, void * pixels);
extern void (*next_glGetTexLevelParameterfv)(GLenum target, GLint level, GLenum pname, GLfloat* params);
extern void (*next_glGetTexLevelParameteriv)(GLenum target, GLint level, GLenum pname, GLint* params);
extern void (*next_glGetTexParameterfv)(GLenum target, GLenum pname, GLfloat* params);
extern void (*next_glGetTexParameteriv)(GLenum target, GLenum pname, GLint* params);
extern void (*next_glHint)(GLenum target, GLenum mode);
extern void (*next_glIndexMask)(GLuint mask);
extern void (*next_glIndexd)(GLdouble c);
extern void (*next_glIndexdv)(const GLdouble* c);
extern void (*next_glIndexf)(GLfloat c);
extern void (*next_glIndexfv)(const GLfloat* c);
extern void (*next_glIndexi)(GLint c);
extern void (*next_glIndexiv)(const GLint* c);
extern void (*next_glIndexs)(GLshort c);
extern void (*next_glIndexsv)(const GLshort* c);
extern void (*next_glInitNames)();
extern GLboolean (*next_glIsEnabled)(GLenum cap);
extern GLboolean (*next_glIsList)(GLuint list);
extern void (*next_glLightModelf)(GLenum pname, GLfloat param);
extern void (*next_glLightModelfv)(GLenum pname, const GLfloat* params);
extern void (*next_glLightModeli)(GLenum pname, GLint param);
extern void (*next_glLightModeliv)(GLenum pname, const GLint* params);
extern void (*next_glLightf)(GLenum light, GLenum pname, GLfloat param);
extern void (*next_glLightfv)(GLenum light, GLenum pname, const GLfloat* params);
extern void (*next_glLighti)(GLenum light, GLenum pname, GLint param);
extern void (*next_glLightiv)(GLenum light, GLenum pname, const GLint* params);
extern void (*next_glLineStipple)(GLint factor, GLushort pattern);
extern void (*next_glLineWidth)(GLfloat width);
extern void (*next_glListBase)(GLuint base);
extern void (*next_glLoadIdentity)();
extern void (*next_glLoadMatrixd)(const GLdouble* m);
extern void (*next_glLoadMatrixf)(const GLfloat* m);
extern void (*next_glLoadName)(GLuint name);
extern void (*next_glLogicOp)(GLenum opcode);
extern void (*next_glMap1d)(GLenum target, GLdouble u1, GLdouble u2, GLint stride, GLint order, const GLdouble* points);
extern void (*next_glMap1f)(GLenum target, GLfloat u1, GLfloat u2, GLint stride, GLint order, const GLfloat* points);
extern void (*next_glMap2d)(GLenum target, GLdouble u1, GLdouble u2, GLint ustride, GLint uorder, GLdouble v1, GLdouble v2, GLint vstride, GLint vorder, const GLdouble* points);
extern void (*next_glMap2f)(GLenum target, GLfloat u1, GLfloat u2, GLint ustride, GLint uorder, GLfloat v1, GLfloat v2, GLint vstride, GLint vorder, const GLfloat* points);
extern void (*next_glMapGrid1d)(GLint un, GLdouble u1, GLdouble u2);
extern void (*next_glMapGrid1f)(GLint un, GLfloat u1, GLfloat u2);
extern void (*next_glMapGrid2d)(GLint un, GLdouble u1, GLdouble u2, GLint vn, GLdouble v1, GLdouble v2);
extern void (*next_glMapGrid2f)(GLint un, GLfloat u1, GLfloat u2, GLint vn, GLfloat v1, GLfloat v2);
extern void (*next_glMaterialf)(GLenum face, GLenum pname, GLfloat param);
extern void (*next_glMaterialfv)(GLenum face, GLenum pname, const GLfloat* params);
extern void (*next_glMateriali)(GLenum face, GLenum pname, GLint param);
extern void (*next_glMaterialiv)(GLenum face, GLenum pname, const GLint* params);
extern void (*next_glMatrixMode)(GLenum mode);
extern void (*next_glMultMatrixd)(const GLdouble* m);
extern void (*next_glMultMatrixf)(const GLfloat* m);
extern void (*next_glNewList)(GLuint list, GLenum mode);
extern void (*next_glNormal3b)(GLbyte nx, GLbyte ny, GLbyte nz);
extern void (*next_glNormal3bv)(const GLbyte* v);
extern void (*next_glNormal3d)(GLdouble nx, GLdouble ny, GLdouble nz);
extern void (*next_glNormal3dv)(const GLdouble* v);
extern void (*next_glNormal3f)(GLfloat nx, GLfloat ny, GLfloat nz);
extern void (*next_glNormal3fv)(const GLfloat* v);
extern void (*next_glNormal3i)(GLint nx, GLint ny, GLint nz);
extern void (*next_glNormal3iv)(const GLint* v);
extern void (*next_glNormal3s)(GLshort nx, GLshort ny, GLshort nz);
extern void (*next_glNormal3sv)(const GLshort* v);
extern void (*next_glOrtho)(GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar);
extern void (*next_glPassThrough)(GLfloat token);
extern void (*next_glPixelMapfv)(GLenum map, GLsizei mapsize, const GLfloat* values);
extern void (*next_glPixelMapuiv)(GLenum map, GLsizei mapsize, const GLuint* values);
extern void (*next_glPixelMapusv)(GLenum map, GLsizei mapsize, const GLushort* values);
extern void (*next_glPixelStoref)(GLenum pname, GLfloat param);
extern void (*next_glPixelStorei)(GLenum pname, GLint param);
extern void (*next_glPixelTransferf)(GLenum pname, GLfloat param);
extern void (*next_glPixelTransferi)(GLenum pname, GLint param);
extern void (*next_glPixelZoom)(GLfloat xfactor, GLfloat yfactor);
extern void (*next_glPointSize)(GLfloat size);
extern void (*next_glPolygonMode)(GLenum face, GLenum mode);
extern void (*next_glPolygonStipple)(const GLubyte* mask);
extern void (*next_glPopAttrib)();
extern void (*next_glPopMatrix)();
extern void (*next_glPopName)();
extern void (*next_glPushAttrib)(GLbitfield mask);
extern void (*next_glPushMatrix)();
extern void (*next_glPushName)(GLuint name);
extern void (*next_glRasterPos2d)(GLdouble x, GLdouble y);
extern void (*next_glRasterPos2dv)(const GLdouble* v);
extern void (*next_glRasterPos2f)(GLfloat x, GLfloat y);
extern void (*next_glRasterPos2fv)(const GLfloat* v);
extern void (*next_glRasterPos2i)(GLint x, GLint y);
extern void (*next_glRasterPos2iv)(const GLint* v);
extern void (*next_glRasterPos2s)(GLshort x, GLshort y);
extern void (*next_glRasterPos2sv)(const GLshort* v);
extern void (*next_glRasterPos3d)(GLdouble x, GLdouble y, GLdouble z);
extern void (*next_glRasterPos3dv)(const GLdouble* v);
extern void (*next_glRasterPos3f)(GLfloat x, GLfloat y, GLfloat z);
extern void (*next_glRasterPos3fv)(const GLfloat* v);
extern void (*next_glRasterPos3i)(GLint x, GLint y, GLint z);
extern void (*next_glRasterPos3iv)(const GLint* v);
extern void (*next_glRasterPos3s)(GLshort x, GLshort y, GLshort z);
extern void (*next_glRasterPos3sv)(const GLshort* v);
extern void (*next_glRasterPos4d)(GLdouble x, GLdouble y, GLdouble z, GLdouble w);
extern void (*next_glRasterPos4dv)(const GLdouble* v);
extern void (*next_glRasterPos4f)(GLfloat x, GLfloat y, GLfloat z, GLfloat w);
extern void (*next_glRasterPos4fv)(const GLfloat* v);
extern void (*next_glRasterPos4i)(GLint x, GLint y, GLint z, GLint w);
extern void (*next_glRasterPos4iv)(const GLint* v);
extern void (*next_glRasterPos4s)(GLshort x, GLshort y, GLshort z, GLshort w);
extern void (*next_glRasterPos4sv)(const GLshort* v);
extern void (*next_glReadBuffer)(GLenum src);
extern void (*next_glReadPixels)(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, void * pixels);
extern void (*next_glRectd)(GLdouble x1, GLdouble y1, GLdouble x2, GLdouble y2);
extern void (*next_glRectdv)(const GLdouble* v1, const GLdouble* v2);
extern void (*next_glRectf)(GLfloat x1, GLfloat y1, GLfloat x2, GLfloat y2);
extern void (*next_glRectfv)(const GLfloat* v1, const GLfloat* v2);
extern void (*next_glRecti)(GLint x1, GLint y1, GLint x2, GLint y2);
extern void (*next_glRectiv)(const GLint* v1, const GLint* v2);
extern void (*next_glRects)(GLshort x1, GLshort y1, GLshort x2, GLshort y2);
extern void (*next_glRectsv)(const GLshort* v1, const GLshort* v2);
extern GLint (*next_glRenderMode)(GLenum mode);
extern void (*next_glRotated)(GLdouble angle, GLdouble x, GLdouble y, GLdouble z);
extern void (*next_glRotatef)(GLfloat angle, GLfloat x, GLfloat y, GLfloat z);
extern void (*next_glScaled)(GLdouble x, GLdouble y, GLdouble z);
extern void (*next_glScalef)(GLfloat x, GLfloat y, GLfloat z);
extern void (*next_glScissor)(GLint x, GLint y, GLsizei width, GLsizei height);
extern void (*next_glSelectBuffer)(GLsizei size, GLuint* buffer);
extern void (*next_glShadeModel)(GLenum mode);
extern void (*next_glStencilFunc)(GLenum func, GLint ref, GLuint mask);
extern void (*next_glStencilMask)(GLuint mask);
extern void (*next_glStencilOp)(GLenum fail, GLenum zfail, GLenum zpass);
extern void (*next_glTexCoord1d)(GLdouble s);
extern void (*next_glTexCoord1dv)(const GLdouble* v);
extern void (*next_glTexCoord1f)(GLfloat s);
extern void (*next_glTexCoord1fv)(const GLfloat* v);
extern void (*next_glTexCoord1i)(GLint s);
extern void (*next_glTexCoord1iv)(const GLint* v);
extern void (*next_glTexCoord1s)(GLshort s);
extern void (*next_glTexCoord1sv)(const GLshort* v);
extern void (*next_glTexCoord2d)(GLdouble s, GLdouble t);
extern void (*next_glTexCoord2dv)(const GLdouble* v);
extern void (*next_glTexCoord2f)(GLfloat s, GLfloat t);
extern void (*next_glTexCoord2fv)(const GLfloat* v);
extern void (*next_glTexCoord2i)(GLint s, GLint t);
extern void (*next_glTexCoord2iv)(const GLint* v);
extern void (*next_glTexCoord2s)(GLshort s, GLshort t);
extern void (*next_glTexCoord2sv)(const GLshort* v);
extern void (*next_glTexCoord3d)(GLdouble s, GLdouble t, GLdouble r);
extern void (*next_glTexCoord3dv)(const GLdouble* v);
extern void (*next_glTexCoord3f)(GLfloat s, GLfloat t, GLfloat r);
extern void (*next_glTexCoord3fv)(const GLfloat* v);
extern void (*next_glTexCoord3i)(GLint s, GLint t, GLint r);
extern void (*next_glTexCoord3iv)(const GLint* v);
extern void (*next_glTexCoord3s)(GLshort s, GLshort t, GLshort r);
extern void (*next_glTexCoord3sv)(const GLshort* v);
extern void (*next_glTexCoord4d)(GLdouble s, GLdouble t, GLdouble r, GLdouble q);
extern void (*next_glTexCoord4dv)(const GLdouble* v);
extern void (*next_glTexCoord4f)(GLfloat s, GLfloat t, GLfloat r, GLfloat q);
extern void (*next_glTexCoord4fv)(const GLfloat* v);
extern void (*next_glTexCoord4i)(GLint s, GLint t, GLint r, GLint q);
extern void (*next_glTexCoord4iv)(const GLint* v);
extern void (*next_glTexCoord4s)(GLshort s, GLshort t, GLshort r, GLshort q);
extern void (*next_glTexCoord4sv)(const GLshort* v);
extern void (*next_glTexEnvf)(GLenum target, GLenum pname, GLfloat param);
extern void (*next_glTexEnvfv)(GLenum target, GLenum pname, const GLfloat* params);
extern void (*next_glTexEnvi)(GLenum target, GLenum pname, GLint param);
extern void (*next_glTexEnviv)(GLenum target, GLenum pname, const GLint* params);
extern void (*next_glTexGend)(GLenum coord, GLenum pname, GLdouble param);
extern void (*next_glTexGendv)(GLenum coord, GLenum pname, const GLdouble* params);
extern void (*next_glTexGenf)(GLenum coord, GLenum pname, GLfloat param);
extern void (*next_glTexGenfv)(GLenum coord, GLenum pname, const GLfloat* params);
extern void (*next_glTexGeni)(GLenum coord, GLenum pname, GLint param);
extern void (*next_glTexGeniv)(GLenum coord, GLenum pname, const GLint* params);
extern void (*next_glTexImage1D)(GLenum target, GLint level, GLint internalformat, GLsizei width, GLint border, GLenum format, GLenum type, const void * pixels);
extern void (*next_glTexImage2D)(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const void * pixels);
extern void (*next_glTexParameterf)(GLenum target, GLenum pname, GLfloat param);
extern void (*next_glTexParameterfv)(GLenum target, GLenum pname, const GLfloat* params);
extern void (*next_glTexParameteri)(GLenum target, GLenum pname, GLint param);
extern void (*next_glTexParameteriv)(GLenum target, GLenum pname, const GLint* params);
extern void (*next_glTranslated)(GLdouble x, GLdouble y, GLdouble z);
extern void (*next_glTranslatef)(GLfloat x, GLfloat y, GLfloat z);
extern void (*next_glVertex2d)(GLdouble x, GLdouble y);
extern void (*next_glVertex2dv)(const GLdouble* v);
extern void (*next_glVertex2f)(GLfloat x, GLfloat y);
extern void (*next_glVertex2fv)(const GLfloat* v);
extern void (*next_glVertex2i)(GLint x, GLint y);
extern void (*next_glVertex2iv)(const GLint* v);
extern void (*next_glVertex2s)(GLshort x, GLshort y);
extern void (*next_glVertex2sv)(const GLshort* v);
extern void (*next_glVertex3d)(GLdouble x, GLdouble y, GLdouble z);
extern void (*next_glVertex3dv)(const GLdouble* v);
extern void (*next_glVertex3f)(GLfloat x, GLfloat y, GLfloat z);
extern void (*next_glVertex3fv)(const GLfloat* v);
extern void (*next_glVertex3i)(GLint x, GLint y, GLint z);
extern void (*next_glVertex3iv)(const GLint* v);
extern void (*next_glVertex3s)(GLshort x, GLshort y, GLshort z);
extern void (*next_glVertex3sv)(const GLshort* v);
extern void (*next_glVertex4d)(GLdouble x, GLdouble y, GLdouble z, GLdouble w);
extern void (*next_glVertex4dv)(const GLdouble* v);
extern void (*next_glVertex4f)(GLfloat x, GLfloat y, GLfloat z, GLfloat w);
extern void (*next_glVertex4fv)(const GLfloat* v);
extern void (*next_glVertex4i)(GLint x, GLint y, GLint z, GLint w);
extern void (*next_glVertex4iv)(const GLint* v);
extern void (*next_glVertex4s)(GLshort x, GLshort y, GLshort z, GLshort w);
extern void (*next_glVertex4sv)(const GLshort* v);
extern void (*next_glViewport)(GLint x, GLint y, GLsizei width, GLsizei height);


// GL_VERSION_1_1

extern GLboolean (*next_glAreTexturesResident)(GLsizei n, const GLuint* textures, GLboolean* residences);
extern void (*next_glArrayElement)(GLint i);
extern void (*next_glBindTexture)(GLenum target, GLuint texture);
extern void (*next_glColorPointer)(GLint size, GLenum type, GLsizei stride, const void * pointer);
extern void (*next_glCopyTexImage1D)(GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLint border);
extern void (*next_glCopyTexImage2D)(GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border);
extern void (*next_glCopyTexSubImage1D)(GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width);
extern void (*next_glCopyTexSubImage2D)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height);
extern void (*next_glDeleteTextures)(GLsizei n, const GLuint* textures);
extern void (*next_glDisableClientState)(GLenum array);
extern void (*next_glDrawArrays)(GLenum mode, GLint first, GLsizei count);
extern void (*next_glDrawElements)(GLenum mode, GLsizei count, GLenum type, const void * indices);
extern void (*next_glEdgeFlagPointer)(GLsizei stride, const void * pointer);
extern void (*next_glEnableClientState)(GLenum array);
extern void (*next_glGenTextures)(GLsizei n, GLuint* textures);
extern void (*next_glGetPointerv)(GLenum pname, void ** params);
extern void (*next_glIndexPointer)(GLenum type, GLsizei stride, const void * pointer);
extern void (*next_glIndexub)(GLubyte c);
extern void (*next_glIndexubv)(const GLubyte* c);
extern void (*next_glInterleavedArrays)(GLenum format, GLsizei stride, const void * pointer);
extern GLboolean (*next_glIsTexture)(GLuint texture);
extern void (*next_glNormalPointer)(GLenum type, GLsizei stride, const void * pointer);
extern void (*next_glPolygonOffset)(GLfloat factor, GLfloat units);
extern void (*next_glPopClientAttrib)();
extern void (*next_glPrioritizeTextures)(GLsizei n, const GLuint* textures, const GLfloat* priorities);
extern void (*next_glPushClientAttrib)(GLbitfield mask);
extern void (*next_glTexCoordPointer)(GLint size, GLenum type, GLsizei stride, const void * pointer);
extern void (*next_glTexSubImage1D)(GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const void * pixels);
extern void (*next_glTexSubImage2D)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const void * pixels);
extern void (*next_glVertexPointer)(GLint size, GLenum type, GLsizei stride, const void * pointer);


// GL_VERSION_1_2

extern void (*next_glCopyTexSubImage3D)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height);
extern void (*next_glDrawRangeElements)(GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const void * indices);
extern void (*next_glTexImage3D)(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const void * pixels);
extern void (*next_glTexSubImage3D)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const void * pixels);


// GL_VERSION_1_3

extern void (*next_glActiveTexture)(GLenum texture);
extern void (*next_glClientActiveTexture)(GLenum texture);
extern void (*next_glCompressedTexImage1D)(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLint border, GLsizei imageSize, const void * data);
extern void (*next_glCompressedTexImage2D)(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const void * data);
extern void (*next_glCompressedTexImage3D)(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLsizei imageSize, const void * data);
extern void (*next_glCompressedTexSubImage1D)(GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLsizei imageSize, const void * data);
extern void (*next_glCompressedTexSubImage2D)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const void * data);
extern void (*next_glCompressedTexSubImage3D)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const void * data);
extern void (*next_glGetCompressedTexImage)(GLenum target, GLint level, void * img);
extern void (*next_glLoadTransposeMatrixd)(const GLdouble* m);
extern void (*next_glLoadTransposeMatrixf)(const GLfloat* m);
extern void (*next_glMultTransposeMatrixd)(const GLdouble* m);
extern void (*next_glMultTransposeMatrixf)(const GLfloat* m);
extern void (*next_glMultiTexCoord1d)(GLenum target, GLdouble s);
extern void (*next_glMultiTexCoord1dv)(GLenum target, const GLdouble* v);
extern void (*next_glMultiTexCoord1f)(GLenum target, GLfloat s);
extern void (*next_glMultiTexCoord1fv)(GLenum target, const GLfloat* v);
extern void (*next_glMultiTexCoord1i)(GLenum target, GLint s);
extern void (*next_glMultiTexCoord1iv)(GLenum target, const GLint* v);
extern void (*next_glMultiTexCoord1s)(GLenum target, GLshort s);
extern void (*next_glMultiTexCoord1sv)(GLenum target, const GLshort* v);
extern void (*next_glMultiTexCoord2d)(GLenum target, GLdouble s, GLdouble t);
extern void (*next_glMultiTexCoord2dv)(GLenum target, const GLdouble* v);
extern void (*next_glMultiTexCoord2f)(GLenum target, GLfloat s, GLfloat t);
extern void (*next_glMultiTexCoord2fv)(GLenum target, const GLfloat* v);
extern void (*next_glMultiTexCoord2i)(GLenum target, GLint s, GLint t);
extern void (*next_glMultiTexCoord2iv)(GLenum target, const GLint* v);
extern void (*next_glMultiTexCoord2s)(GLenum target, GLshort s, GLshort t);
extern void (*next_glMultiTexCoord2sv)(GLenum target, const GLshort* v);
extern void (*next_glMultiTexCoord3d)(GLenum target, GLdouble s, GLdouble t, GLdouble r);
extern void (*next_glMultiTexCoord3dv)(GLenum target, const GLdouble* v);
extern void (*next_glMultiTexCoord3f)(GLenum target, GLfloat s, GLfloat t, GLfloat r);
extern void (*next_glMultiTexCoord3fv)(GLenum target, const GLfloat* v);
extern void (*next_glMultiTexCoord3i)(GLenum target, GLint s, GLint t, GLint r);
extern void (*next_glMultiTexCoord3iv)(GLenum target, const GLint* v);
extern void (*next_glMultiTexCoord3s)(GLenum target, GLshort s, GLshort t, GLshort r);
extern void (*next_glMultiTexCoord3sv)(GLenum target, const GLshort* v);
extern void (*next_glMultiTexCoord4d)(GLenum target, GLdouble s, GLdouble t, GLdouble r, GLdouble q);
extern void (*next_glMultiTexCoord4dv)(GLenum target, const GLdouble* v);
extern void (*next_glMultiTexCoord4f)(GLenum target, GLfloat s, GLfloat t, GLfloat r, GLfloat q);
extern void (*next_glMultiTexCoord4fv)(GLenum target, const GLfloat* v);
extern void (*next_glMultiTexCoord4i)(GLenum target, GLint s, GLint t, GLint r, GLint q);
extern void (*next_glMultiTexCoord4iv)(GLenum target, const GLint* v);
extern void (*next_glMultiTexCoord4s)(GLenum target, GLshort s, GLshort t, GLshort r, GLshort q);
extern void (*next_glMultiTexCoord4sv)(GLenum target, const GLshort* v);
extern void (*next_glSampleCoverage)(GLfloat value, GLboolean invert);


// GL_VERSION_1_4

extern void (*next_glBlendColor)(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
extern void (*next_glBlendEquation)(GLenum mode);
extern void (*next_glBlendFuncSeparate)(GLenum sfactorRGB, GLenum dfactorRGB, GLenum sfactorAlpha, GLenum dfactorAlpha);
extern void (*next_glFogCoordPointer)(GLenum type, GLsizei stride, const void * pointer);
extern void (*next_glFogCoordd)(GLdouble coord);
extern void (*next_glFogCoorddv)(const GLdouble* coord);
extern void (*next_glFogCoordf)(GLfloat coord);
extern void (*next_glFogCoordfv)(const GLfloat* coord);
extern void (*next_glMultiDrawArrays)(GLenum mode, const GLint* first, const GLsizei* count, GLsizei drawcount);
extern void (*next_glMultiDrawElements)(GLenum mode, const GLsizei* count, GLenum type, const void *const* indices, GLsizei drawcount);
extern void (*next_glPointParameterf)(GLenum pname, GLfloat param);
extern void (*next_glPointParameterfv)(GLenum pname, const GLfloat* params);
extern void (*next_glPointParameteri)(GLenum pname, GLint param);
extern void (*next_glPointParameteriv)(GLenum pname, const GLint* params);
extern void (*next_glSecondaryColor3b)(GLbyte red, GLbyte green, GLbyte blue);
extern void (*next_glSecondaryColor3bv)(const GLbyte* v);
extern void (*next_glSecondaryColor3d)(GLdouble red, GLdouble green, GLdouble blue);
extern void (*next_glSecondaryColor3dv)(const GLdouble* v);
extern void (*next_glSecondaryColor3f)(GLfloat red, GLfloat green, GLfloat blue);
extern void (*next_glSecondaryColor3fv)(const GLfloat* v);
extern void (*next_glSecondaryColor3i)(GLint red, GLint green, GLint blue);
extern void (*next_glSecondaryColor3iv)(const GLint* v);
extern void (*next_glSecondaryColor3s)(GLshort red, GLshort green, GLshort blue);
extern void (*next_glSecondaryColor3sv)(const GLshort* v);
extern void (*next_glSecondaryColor3ub)(GLubyte red, GLubyte green, GLubyte blue);
extern void (*next_glSecondaryColor3ubv)(const GLubyte* v);
extern void (*next_glSecondaryColor3ui)(GLuint red, GLuint green, GLuint blue);
extern void (*next_glSecondaryColor3uiv)(const GLuint* v);
extern void (*next_glSecondaryColor3us)(GLushort red, GLushort green, GLushort blue);
extern void (*next_glSecondaryColor3usv)(const GLushort* v);
extern void (*next_glSecondaryColorPointer)(GLint size, GLenum type, GLsizei stride, const void * pointer);
extern void (*next_glWindowPos2d)(GLdouble x, GLdouble y);
extern void (*next_glWindowPos2dv)(const GLdouble* v);
extern void (*next_glWindowPos2f)(GLfloat x, GLfloat y);
extern void (*next_glWindowPos2fv)(const GLfloat* v);
extern void (*next_glWindowPos2i)(GLint x, GLint y);
extern void (*next_glWindowPos2iv)(const GLint* v);
extern void (*next_glWindowPos2s)(GLshort x, GLshort y);
extern void (*next_glWindowPos2sv)(const GLshort* v);
extern void (*next_glWindowPos3d)(GLdouble x, GLdouble y, GLdouble z);
extern void (*next_glWindowPos3dv)(const GLdouble* v);
extern void (*next_glWindowPos3f)(GLfloat x, GLfloat y, GLfloat z);
extern void (*next_glWindowPos3fv)(const GLfloat* v);
extern void (*next_glWindowPos3i)(GLint x, GLint y, GLint z);
extern void (*next_glWindowPos3iv)(const GLint* v);
extern void (*next_glWindowPos3s)(GLshort x, GLshort y, GLshort z);
extern void (*next_glWindowPos3sv)(const GLshort* v);


// GL_VERSION_1_5

extern void (*next_glBeginQuery)(GLenum target, GLuint id);
extern void (*next_glBindBuffer)(GLenum target, GLuint buffer);
extern void (*next_glBufferData)(GLenum target, GLsizeiptr size, const void * data, GLenum usage);
extern void (*next_glBufferSubData)(GLenum target, GLintptr offset, GLsizeiptr size, const void * data);
extern void (*next_glDeleteBuffers)(GLsizei n, const GLuint* buffers);
extern void (*next_glDeleteQueries)(GLsizei n, const GLuint* ids);
extern void (*next_glEndQuery)(GLenum target);
extern void (*next_glGenBuffers)(GLsizei n, GLuint* buffers);
extern void (*next_glGenQueries)(GLsizei n, GLuint* ids);
extern void (*next_glGetBufferParameteriv)(GLenum target, GLenum pname, GLint* params);
extern void (*next_glGetBufferPointerv)(GLenum target, GLenum pname, void ** params);
extern void (*next_glGetBufferSubData)(GLenum target, GLintptr offset, GLsizeiptr size, void * data);
extern void (*next_glGetQueryObjectiv)(GLuint id, GLenum pname, GLint* params);
extern void (*next_glGetQueryObjectuiv)(GLuint id, GLenum pname, GLuint* params);
extern void (*next_glGetQueryiv)(GLenum target, GLenum pname, GLint* params);
extern GLboolean (*next_glIsBuffer)(GLuint buffer);
extern GLboolean (*next_glIsQuery)(GLuint id);
extern void * (*next_glMapBuffer)(GLenum target, GLenum access);
extern GLboolean (*next_glUnmapBuffer)(GLenum target);


// GL_VERSION_2_0

extern void (*next_glAttachShader)(GLuint program, GLuint shader);
extern void (*next_glBindAttribLocation)(GLuint program, GLuint index, const GLchar* name);
extern void (*next_glBlendEquationSeparate)(GLenum modeRGB, GLenum modeAlpha);
extern void (*next_glCompileShader)(GLuint shader);
extern GLuint (*next_glCreateProgram)();
extern GLuint (*next_glCreateShader)(GLenum type);
extern void (*next_glDeleteProgram)(GLuint program);
extern void (*next_glDeleteShader)(GLuint shader);
extern void (*next_glDetachShader)(GLuint program, GLuint shader);
extern void (*next_glDisableVertexAttribArray)(GLuint index);
extern void (*next_glDrawBuffers)(GLsizei n, const GLenum* bufs);
extern void (*next_glEnableVertexAttribArray)(GLuint index);
extern void (*next_glGetActiveAttrib)(GLuint program, GLuint index, GLsizei bufSize, GLsizei* length, GLint* size, GLenum* type, GLchar* name);
extern void (*next_glGetActiveUniform)(GLuint program, GLuint index, GLsizei bufSize, GLsizei* length, GLint* size, GLenum* type, GLchar* name);
extern void (*next_glGetAttachedShaders)(GLuint program, GLsizei maxCount, GLsizei* count, GLuint* shaders);
extern GLint (*next_glGetAttribLocation)(GLuint program, const GLchar* name);
extern void (*next_glGetProgramInfoLog)(GLuint program, GLsizei bufSize, GLsizei* length, GLchar* infoLog);
extern void (*next_glGetProgramiv)(GLuint program, GLenum pname, GLint* params);
extern void (*next_glGetShaderInfoLog)(GLuint shader, GLsizei bufSize, GLsizei* length, GLchar* infoLog);
extern void (*next_glGetShaderSource)(GLuint shader, GLsizei bufSize, GLsizei* length, GLchar* source);
extern void (*next_glGetShaderiv)(GLuint shader, GLenum pname, GLint* params);
extern GLint (*next_glGetUniformLocation)(GLuint program, const GLchar* name);
extern void (*next_glGetUniformfv)(GLuint program, GLint location, GLfloat* params);
extern void (*next_glGetUniformiv)(GLuint program, GLint location, GLint* params);
extern void (*next_glGetVertexAttribPointerv)(GLuint index, GLenum pname, void ** pointer);
extern void (*next_glGetVertexAttribdv)(GLuint index, GLenum pname, GLdouble* params);
extern void (*next_glGetVertexAttribfv)(GLuint index, GLenum pname, GLfloat* params);
extern void (*next_glGetVertexAttribiv)(GLuint index, GLenum pname, GLint* params);
extern GLboolean (*next_glIsProgram)(GLuint program);
extern GLboolean (*next_glIsShader)(GLuint shader);
extern void (*next_glLinkProgram)(GLuint program);
extern void (*next_glShaderSource)(GLuint shader, GLsizei count, const GLchar*const* string, const GLint* length);
extern void (*next_glStencilFuncSeparate)(GLenum face, GLenum func, GLint ref, GLuint mask);
extern void (*next_glStencilMaskSeparate)(GLenum face, GLuint mask);
extern void (*next_glStencilOpSeparate)(GLenum face, GLenum sfail, GLenum dpfail, GLenum dppass);
extern void (*next_glUniform1f)(GLint location, GLfloat v0);
extern void (*next_glUniform1fv)(GLint location, GLsizei count, const GLfloat* value);
extern void (*next_glUniform1i)(GLint location, GLint v0);
extern void (*next_glUniform1iv)(GLint location, GLsizei count, const GLint* value);
extern void (*next_glUniform2f)(GLint location, GLfloat v0, GLfloat v1);
extern void (*next_glUniform2fv)(GLint location, GLsizei count, const GLfloat* value);
extern void (*next_glUniform2i)(GLint location, GLint v0, GLint v1);
extern void (*next_glUniform2iv)(GLint location, GLsizei count, const GLint* value);
extern void (*next_glUniform3f)(GLint location, GLfloat v0, GLfloat v1, GLfloat v2);
extern void (*next_glUniform3fv)(GLint location, GLsizei count, const GLfloat* value);
extern void (*next_glUniform3i)(GLint location, GLint v0, GLint v1, GLint v2);
extern void (*next_glUniform3iv)(GLint location, GLsizei count, const GLint* value);
extern void (*next_glUniform4f)(GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3);
extern void (*next_glUniform4fv)(GLint location, GLsizei count, const GLfloat* value);
extern void (*next_glUniform4i)(GLint location, GLint v0, GLint v1, GLint v2, GLint v3);
extern void (*next_glUniform4iv)(GLint location, GLsizei count, const GLint* value);
extern void (*next_glUniformMatrix2fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
extern void (*next_glUniformMatrix3fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
extern void (*next_glUniformMatrix4fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
extern void (*next_glUseProgram)(GLuint program);
extern void (*next_glValidateProgram)(GLuint program);
extern void (*next_glVertexAttrib1d)(GLuint index, GLdouble x);
extern void (*next_glVertexAttrib1dv)(GLuint index, const GLdouble* v);
extern void (*next_glVertexAttrib1f)(GLuint index, GLfloat x);
extern void (*next_glVertexAttrib1fv)(GLuint index, const GLfloat* v);
extern void (*next_glVertexAttrib1s)(GLuint index, GLshort x);
extern void (*next_glVertexAttrib1sv)(GLuint index, const GLshort* v);
extern void (*next_glVertexAttrib2d)(GLuint index, GLdouble x, GLdouble y);
extern void (*next_glVertexAttrib2dv)(GLuint index, const GLdouble* v);
extern void (*next_glVertexAttrib2f)(GLuint index, GLfloat x, GLfloat y);
extern void (*next_glVertexAttrib2fv)(GLuint index, const GLfloat* v);
extern void (*next_glVertexAttrib2s)(GLuint index, GLshort x, GLshort y);
extern void (*next_glVertexAttrib2sv)(GLuint index, const GLshort* v);
extern void (*next_glVertexAttrib3d)(GLuint index, GLdouble x, GLdouble y, GLdouble z);
extern void (*next_glVertexAttrib3dv)(GLuint index, const GLdouble* v);
extern void (*next_glVertexAttrib3f)(GLuint index, GLfloat x, GLfloat y, GLfloat z);
extern void (*next_glVertexAttrib3fv)(GLuint index, const GLfloat* v);
extern void (*next_glVertexAttrib3s)(GLuint index, GLshort x, GLshort y, GLshort z);
extern void (*next_glVertexAttrib3sv)(GLuint index, const GLshort* v);
extern void (*next_glVertexAttrib4Nbv)(GLuint index, const GLbyte* v);
extern void (*next_glVertexAttrib4Niv)(GLuint index, const GLint* v);
extern void (*next_glVertexAttrib4Nsv)(GLuint index, const GLshort* v);
extern void (*next_glVertexAttrib4Nub)(GLuint index, GLubyte x, GLubyte y, GLubyte z, GLubyte w);
extern void (*next_glVertexAttrib4Nubv)(GLuint index, const GLubyte* v);
extern void (*next_glVertexAttrib4Nuiv)(GLuint index, const GLuint* v);
extern void (*next_glVertexAttrib4Nusv)(GLuint index, const GLushort* v);
extern void (*next_glVertexAttrib4bv)(GLuint index, const GLbyte* v);
extern void (*next_glVertexAttrib4d)(GLuint index, GLdouble x, GLdouble y, GLdouble z, GLdouble w);
extern void (*next_glVertexAttrib4dv)(GLuint index, const GLdouble* v);
extern void (*next_glVertexAttrib4f)(GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w);
extern void (*next_glVertexAttrib4fv)(GLuint index, const GLfloat* v);
extern void (*next_glVertexAttrib4iv)(GLuint index, const GLint* v);
extern void (*next_glVertexAttrib4s)(GLuint index, GLshort x, GLshort y, GLshort z, GLshort w);
extern void (*next_glVertexAttrib4sv)(GLuint index, const GLshort* v);
extern void (*next_glVertexAttrib4ubv)(GLuint index, const GLubyte* v);
extern void (*next_glVertexAttrib4uiv)(GLuint index, const GLuint* v);
extern void (*next_glVertexAttrib4usv)(GLuint index, const GLushort* v);
extern void (*next_glVertexAttribPointer)(GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const void * pointer);


// GL_VERSION_2_1

extern void (*next_glUniformMatrix2x3fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
extern void (*next_glUniformMatrix2x4fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
extern void (*next_glUniformMatrix3x2fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
extern void (*next_glUniformMatrix3x4fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
extern void (*next_glUniformMatrix4x2fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
extern void (*next_glUniformMatrix4x3fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);


// GL_VERSION_3_0

extern void (*next_glBeginConditionalRender)(GLuint id, GLenum mode);
extern void (*next_glBeginTransformFeedback)(GLenum primitiveMode);
extern void (*next_glBindBufferBase)(GLenum target, GLuint index, GLuint buffer);
extern void (*next_glBindBufferRange)(GLenum target, GLuint index, GLuint buffer, GLintptr offset, GLsizeiptr size);
extern void (*next_glBindFragDataLocation)(GLuint program, GLuint color, const GLchar* name);
extern void (*next_glBindFramebuffer)(GLenum target, GLuint framebuffer);
extern void (*next_glBindRenderbuffer)(GLenum target, GLuint renderbuffer);
extern void (*next_glBindVertexArray)(GLuint array);
extern void (*next_glBlitFramebuffer)(GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter);
extern GLenum (*next_glCheckFramebufferStatus)(GLenum target);
extern void (*next_glClampColor)(GLenum target, GLenum clamp);
extern void (*next_glClearBufferfi)(GLenum buffer, GLint drawbuffer, GLfloat depth, GLint stencil);
extern void (*next_glClearBufferfv)(GLenum buffer, GLint drawbuffer, const GLfloat* value);
extern void (*next_glClearBufferiv)(GLenum buffer, GLint drawbuffer, const GLint* value);
extern void (*next_glClearBufferuiv)(GLenum buffer, GLint drawbuffer, const GLuint* value);
extern void (*next_glColorMaski)(GLuint index, GLboolean r, GLboolean g, GLboolean b, GLboolean a);
extern void (*next_glDeleteFramebuffers)(GLsizei n, const GLuint* framebuffers);
extern void (*next_glDeleteRenderbuffers)(GLsizei n, const GLuint* renderbuffers);
extern void (*next_glDeleteVertexArrays)(GLsizei n, const GLuint* arrays);
extern void (*next_glDisablei)(GLenum target, GLuint index);
extern void (*next_glEnablei)(GLenum target, GLuint index);
extern void (*next_glEndConditionalRender)();
extern void (*next_glEndTransformFeedback)();
extern void (*next_glFlushMappedBufferRange)(GLenum target, GLintptr offset, GLsizeiptr length);
extern void (*next_glFramebufferRenderbuffer)(GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer);
extern void (*next_glFramebufferTexture1D)(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level);
extern void (*next_glFramebufferTexture2D)(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level);
extern void (*next_glFramebufferTexture3D)(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level, GLint zoffset);
extern void (*next_glFramebufferTextureLayer)(GLenum target, GLenum attachment, GLuint texture, GLint level, GLint layer);
extern void (*next_glGenFramebuffers)(GLsizei n, GLuint* framebuffers);
extern void (*next_glGenRenderbuffers)(GLsizei n, GLuint* renderbuffers);
extern void (*next_glGenVertexArrays)(GLsizei n, GLuint* arrays);
extern void (*next_glGenerateMipmap)(GLenum target);
extern void (*next_glGetBooleani_v)(GLenum target, GLuint index, GLboolean* data);
extern GLint (*next_glGetFragDataLocation)(GLuint program, const GLchar* name);
extern void (*next_glGetFramebufferAttachmentParameteriv)(GLenum target, GLenum attachment, GLenum pname, GLint* params);
extern void (*next_glGetIntegeri_v)(GLenum target, GLuint index, GLint* data);
extern void (*next_glGetRenderbufferParameteriv)(GLenum target, GLenum pname, GLint* params);
extern const GLubyte* (*next_glGetStringi)(GLenum name, GLuint index);
extern void (*next_glGetTexParameterIiv)(GLenum target, GLenum pname, GLint* params);
extern void (*next_glGetTexParameterIuiv)(GLenum target, GLenum pname, GLuint* params);
extern void (*next_glGetTransformFeedbackVarying)(GLuint program, GLuint index, GLsizei bufSize, GLsizei* length, GLsizei* size, GLenum* type, GLchar* name);
extern void (*next_glGetUniformuiv)(GLuint program, GLint location, GLuint* params);
extern void (*next_glGetVertexAttribIiv)(GLuint index, GLenum pname, GLint* params);
extern void (*next_glGetVertexAttribIuiv)(GLuint index, GLenum pname, GLuint* params);
extern GLboolean (*next_glIsEnabledi)(GLenum target, GLuint index);
extern GLboolean (*next_glIsFramebuffer)(GLuint framebuffer);
extern GLboolean (*next_glIsRenderbuffer)(GLuint renderbuffer);
extern GLboolean (*next_glIsVertexArray)(GLuint array);
extern void * (*next_glMapBufferRange)(GLenum target, GLintptr offset, GLsizeiptr length, GLbitfield access);
extern void (*next_glRenderbufferStorage)(GLenum target, GLenum internalformat, GLsizei width, GLsizei height);
extern void (*next_glRenderbufferStorageMultisample)(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height);
extern void (*next_glTexParameterIiv)(GLenum target, GLenum pname, const GLint* params);
extern void (*next_glTexParameterIuiv)(GLenum target, GLenum pname, const GLuint* params);
extern void (*next_glTransformFeedbackVaryings)(GLuint program, GLsizei count, const GLchar*const* varyings, GLenum bufferMode);
extern void (*next_glUniform1ui)(GLint location, GLuint v0);
extern void (*next_glUniform1uiv)(GLint location, GLsizei count, const GLuint* value);
extern void (*next_glUniform2ui)(GLint location, GLuint v0, GLuint v1);
extern void (*next_glUniform2uiv)(GLint location, GLsizei count, const GLuint* value);
extern void (*next_glUniform3ui)(GLint location, GLuint v0, GLuint v1, GLuint v2);
extern void (*next_glUniform3uiv)(GLint location, GLsizei count, const GLuint* value);
extern void (*next_glUniform4ui)(GLint location, GLuint v0, GLuint v1, GLuint v2, GLuint v3);
extern void (*next_glUniform4uiv)(GLint location, GLsizei count, const GLuint* value);
extern void (*next_glVertexAttribI1i)(GLuint index, GLint x);
extern void (*next_glVertexAttribI1iv)(GLuint index, const GLint* v);
extern void (*next_glVertexAttribI1ui)(GLuint index, GLuint x);
extern void (*next_glVertexAttribI1uiv)(GLuint index, const GLuint* v);
extern void (*next_glVertexAttribI2i)(GLuint index, GLint x, GLint y);
extern void (*next_glVertexAttribI2iv)(GLuint index, const GLint* v);
extern void (*next_glVertexAttribI2ui)(GLuint index, GLuint x, GLuint y);
extern void (*next_glVertexAttribI2uiv)(GLuint index, const GLuint* v);
extern void (*next_glVertexAttribI3i)(GLuint index, GLint x, GLint y, GLint z);
extern void (*next_glVertexAttribI3iv)(GLuint index, const GLint* v);
extern void (*next_glVertexAttribI3ui)(GLuint index, GLuint x, GLuint y, GLuint z);
extern void (*next_glVertexAttribI3uiv)(GLuint index, const GLuint* v);
extern void (*next_glVertexAttribI4bv)(GLuint index, const GLbyte* v);
extern void (*next_glVertexAttribI4i)(GLuint index, GLint x, GLint y, GLint z, GLint w);
extern void (*next_glVertexAttribI4iv)(GLuint index, const GLint* v);
extern void (*next_glVertexAttribI4sv)(GLuint index, const GLshort* v);
extern void (*next_glVertexAttribI4ubv)(GLuint index, const GLubyte* v);
extern void (*next_glVertexAttribI4ui)(GLuint index, GLuint x, GLuint y, GLuint z, GLuint w);
extern void (*next_glVertexAttribI4uiv)(GLuint index, const GLuint* v);
extern void (*next_glVertexAttribI4usv)(GLuint index, const GLushort* v);
extern void (*next_glVertexAttribIPointer)(GLuint index, GLint size, GLenum type, GLsizei stride, const void * pointer);


// GL_VERSION_3_1

extern void (*next_glCopyBufferSubData)(GLenum readTarget, GLenum writeTarget, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size);
extern void (*next_glDrawArraysInstanced)(GLenum mode, GLint first, GLsizei count, GLsizei instancecount);
extern void (*next_glDrawElementsInstanced)(GLenum mode, GLsizei count, GLenum type, const void * indices, GLsizei instancecount);
extern void (*next_glGetActiveUniformBlockName)(GLuint program, GLuint uniformBlockIndex, GLsizei bufSize, GLsizei* length, GLchar* uniformBlockName);
extern void (*next_glGetActiveUniformBlockiv)(GLuint program, GLuint uniformBlockIndex, GLenum pname, GLint* params);
extern void (*next_glGetActiveUniformName)(GLuint program, GLuint uniformIndex, GLsizei bufSize, GLsizei* length, GLchar* uniformName);
extern void (*next_glGetActiveUniformsiv)(GLuint program, GLsizei uniformCount, const GLuint* uniformIndices, GLenum pname, GLint* params);
extern GLuint (*next_glGetUniformBlockIndex)(GLuint program, const GLchar* uniformBlockName);
extern void (*next_glGetUniformIndices)(GLuint program, GLsizei uniformCount, const GLchar*const* uniformNames, GLuint* uniformIndices);
extern void (*next_glPrimitiveRestartIndex)(GLuint index);
extern void (*next_glTexBuffer)(GLenum target, GLenum internalformat, GLuint buffer);
extern void (*next_glUniformBlockBinding)(GLuint program, GLuint uniformBlockIndex, GLuint uniformBlockBinding);


// GL_VERSION_3_2

extern GLenum (*next_glClientWaitSync)(GLsync sync, GLbitfield flags, GLuint64 timeout);
extern void (*next_glDeleteSync)(GLsync sync);
extern void (*next_glDrawElementsBaseVertex)(GLenum mode, GLsizei count, GLenum type, const void * indices, GLint basevertex);
extern void (*next_glDrawElementsInstancedBaseVertex)(GLenum mode, GLsizei count, GLenum type, const void * indices, GLsizei instancecount, GLint basevertex);
extern void (*next_glDrawRangeElementsBaseVertex)(GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const void * indices, GLint basevertex);
extern GLsync (*next_glFenceSync)(GLenum condition, GLbitfield flags);
extern void (*next_glFramebufferTexture)(GLenum target, GLenum attachment, GLuint texture, GLint level);
extern void (*next_glGetBufferParameteri64v)(GLenum target, GLenum pname, GLint64* params);
extern void (*next_glGetInteger64i_v)(GLenum target, GLuint index, GLint64* data);
extern void (*next_glGetInteger64v)(GLenum pname, GLint64* data);
extern void (*next_glGetMultisamplefv)(GLenum pname, GLuint index, GLfloat* val);
extern void (*next_glGetSynciv)(GLsync sync, GLenum pname, GLsizei bufSize, GLsizei* length, GLint* values);
extern GLboolean (*next_glIsSync)(GLsync sync);
extern void (*next_glMultiDrawElementsBaseVertex)(GLenum mode, const GLsizei* count, GLenum type, const void *const* indices, GLsizei drawcount, const GLint* basevertex);
extern void (*next_glProvokingVertex)(GLenum mode);
extern void (*next_glSampleMaski)(GLuint maskNumber, GLbitfield mask);
extern void (*next_glTexImage2DMultisample)(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLboolean fixedsamplelocations);
extern void (*next_glTexImage3DMultisample)(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLboolean fixedsamplelocations);
extern void (*next_glWaitSync)(GLsync sync, GLbitfield flags, GLuint64 timeout);


// GL_VERSION_3_3

extern void (*next_glBindFragDataLocationIndexed)(GLuint program, GLuint colorNumber, GLuint index, const GLchar* name);
extern void (*next_glBindSampler)(GLuint unit, GLuint sampler);
extern void (*next_glColorP3ui)(GLenum type, GLuint color);
extern void (*next_glColorP3uiv)(GLenum type, const GLuint* color);
extern void (*next_glColorP4ui)(GLenum type, GLuint color);
extern void (*next_glColorP4uiv)(GLenum type, const GLuint* color);
extern void (*next_glDeleteSamplers)(GLsizei count, const GLuint* samplers);
extern void (*next_glGenSamplers)(GLsizei count, GLuint* samplers);
extern GLint (*next_glGetFragDataIndex)(GLuint program, const GLchar* name);
extern void (*next_glGetQueryObjecti64v)(GLuint id, GLenum pname, GLint64* params);
extern void (*next_glGetQueryObjectui64v)(GLuint id, GLenum pname, GLuint64* params);
extern void (*next_glGetSamplerParameterIiv)(GLuint sampler, GLenum pname, GLint* params);
extern void (*next_glGetSamplerParameterIuiv)(GLuint sampler, GLenum pname, GLuint* params);
extern void (*next_glGetSamplerParameterfv)(GLuint sampler, GLenum pname, GLfloat* params);
extern void (*next_glGetSamplerParameteriv)(GLuint sampler, GLenum pname, GLint* params);
extern GLboolean (*next_glIsSampler)(GLuint sampler);
extern void (*next_glMultiTexCoordP1ui)(GLenum texture, GLenum type, GLuint coords);
extern void (*next_glMultiTexCoordP1uiv)(GLenum texture, GLenum type, const GLuint* coords);
extern void (*next_glMultiTexCoordP2ui)(GLenum texture, GLenum type, GLuint coords);
extern void (*next_glMultiTexCoordP2uiv)(GLenum texture, GLenum type, const GLuint* coords);
extern void (*next_glMultiTexCoordP3ui)(GLenum texture, GLenum type, GLuint coords);
extern void (*next_glMultiTexCoordP3uiv)(GLenum texture, GLenum type, const GLuint* coords);
extern void (*next_glMultiTexCoordP4ui)(GLenum texture, GLenum type, GLuint coords);
extern void (*next_glMultiTexCoordP4uiv)(GLenum texture, GLenum type, const GLuint* coords);
extern void (*next_glNormalP3ui)(GLenum type, GLuint coords);
extern void (*next_glNormalP3uiv)(GLenum type, const GLuint* coords);
extern void (*next_glQueryCounter)(GLuint id, GLenum target);
extern void (*next_glSamplerParameterIiv)(GLuint sampler, GLenum pname, const GLint* param);
extern void (*next_glSamplerParameterIuiv)(GLuint sampler, GLenum pname, const GLuint* param);
extern void (*next_glSamplerParameterf)(GLuint sampler, GLenum pname, GLfloat param);
extern void (*next_glSamplerParameterfv)(GLuint sampler, GLenum pname, const GLfloat* param);
extern void (*next_glSamplerParameteri)(GLuint sampler, GLenum pname, GLint param);
extern void (*next_glSamplerParameteriv)(GLuint sampler, GLenum pname, const GLint* param);
extern void (*next_glSecondaryColorP3ui)(GLenum type, GLuint color);
extern void (*next_glSecondaryColorP3uiv)(GLenum type, const GLuint* color);
extern void (*next_glTexCoordP1ui)(GLenum type, GLuint coords);
extern void (*next_glTexCoordP1uiv)(GLenum type, const GLuint* coords);
extern void (*next_glTexCoordP2ui)(GLenum type, GLuint coords);
extern void (*next_glTexCoordP2uiv)(GLenum type, const GLuint* coords);
extern void (*next_glTexCoordP3ui)(GLenum type, GLuint coords);
extern void (*next_glTexCoordP3uiv)(GLenum type, const GLuint* coords);
extern void (*next_glTexCoordP4ui)(GLenum type, GLuint coords);
extern void (*next_glTexCoordP4uiv)(GLenum type, const GLuint* coords);
extern void (*next_glVertexAttribDivisor)(GLuint index, GLuint divisor);
extern void (*next_glVertexAttribP1ui)(GLuint index, GLenum type, GLboolean normalized, GLuint value);
extern void (*next_glVertexAttribP1uiv)(GLuint index, GLenum type, GLboolean normalized, const GLuint* value);
extern void (*next_glVertexAttribP2ui)(GLuint index, GLenum type, GLboolean normalized, GLuint value);
extern void (*next_glVertexAttribP2uiv)(GLuint index, GLenum type, GLboolean normalized, const GLuint* value);
extern void (*next_glVertexAttribP3ui)(GLuint index, GLenum type, GLboolean normalized, GLuint value);
extern void (*next_glVertexAttribP3uiv)(GLuint index, GLenum type, GLboolean normalized, const GLuint* value);
extern void (*next_glVertexAttribP4ui)(GLuint index, GLenum type, GLboolean normalized, GLuint value);
extern void (*next_glVertexAttribP4uiv)(GLuint index, GLenum type, GLboolean normalized, const GLuint* value);
extern void (*next_glVertexP2ui)(GLenum type, GLuint value);
extern void (*next_glVertexP2uiv)(GLenum type, const GLuint* value);
extern void (*next_glVertexP3ui)(GLenum type, GLuint value);
extern void (*next_glVertexP3uiv)(GLenum type, const GLuint* value);
extern void (*next_glVertexP4ui)(GLenum type, GLuint value);
extern void (*next_glVertexP4uiv)(GLenum type, const GLuint* value);


// GL_VERSION_4_0

extern void (*next_glBeginQueryIndexed)(GLenum target, GLuint index, GLuint id);
extern void (*next_glBindTransformFeedback)(GLenum target, GLuint id);
extern void (*next_glBlendEquationSeparatei)(GLuint buf, GLenum modeRGB, GLenum modeAlpha);
extern void (*next_glBlendEquationi)(GLuint buf, GLenum mode);
extern void (*next_glBlendFuncSeparatei)(GLuint buf, GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha);
extern void (*next_glBlendFunci)(GLuint buf, GLenum src, GLenum dst);
extern void (*next_glDeleteTransformFeedbacks)(GLsizei n, const GLuint* ids);
extern void (*next_glDrawArraysIndirect)(GLenum mode, const void * indirect);
extern void (*next_glDrawElementsIndirect)(GLenum mode, GLenum type, const void * indirect);
extern void (*next_glDrawTransformFeedback)(GLenum mode, GLuint id);
extern void (*next_glDrawTransformFeedbackStream)(GLenum mode, GLuint id, GLuint stream);
extern void (*next_glEndQueryIndexed)(GLenum target, GLuint index);
extern void (*next_glGenTransformFeedbacks)(GLsizei n, GLuint* ids);
extern void (*next_glGetActiveSubroutineName)(GLuint program, GLenum shadertype, GLuint index, GLsizei bufsize, GLsizei* length, GLchar* name);
extern void (*next_glGetActiveSubroutineUniformName)(GLuint program, GLenum shadertype, GLuint index, GLsizei bufsize, GLsizei* length, GLchar* name);
extern void (*next_glGetActiveSubroutineUniformiv)(GLuint program, GLenum shadertype, GLuint index, GLenum pname, GLint* values);
extern void (*next_glGetProgramStageiv)(GLuint program, GLenum shadertype, GLenum pname, GLint* values);
extern void (*next_glGetQueryIndexediv)(GLenum target, GLuint index, GLenum pname, GLint* params);
extern GLuint (*next_glGetSubroutineIndex)(GLuint program, GLenum shadertype, const GLchar* name);
extern GLint (*next_glGetSubroutineUniformLocation)(GLuint program, GLenum shadertype, const GLchar* name);
extern void (*next_glGetUniformSubroutineuiv)(GLenum shadertype, GLint location, GLuint* params);
extern void (*next_glGetUniformdv)(GLuint program, GLint location, GLdouble* params);
extern GLboolean (*next_glIsTransformFeedback)(GLuint id);
extern void (*next_glMinSampleShading)(GLfloat value);
extern void (*next_glPatchParameterfv)(GLenum pname, const GLfloat* values);
extern void (*next_glPatchParameteri)(GLenum pname, GLint value);
extern void (*next_glPauseTransformFeedback)();
extern void (*next_glResumeTransformFeedback)();
extern void (*next_glUniform1d)(GLint location, GLdouble x);
extern void (*next_glUniform1dv)(GLint location, GLsizei count, const GLdouble* value);
extern void (*next_glUniform2d)(GLint location, GLdouble x, GLdouble y);
extern void (*next_glUniform2dv)(GLint location, GLsizei count, const GLdouble* value);
extern void (*next_glUniform3d)(GLint location, GLdouble x, GLdouble y, GLdouble z);
extern void (*next_glUniform3dv)(GLint location, GLsizei count, const GLdouble* value);
extern void (*next_glUniform4d)(GLint location, GLdouble x, GLdouble y, GLdouble z, GLdouble w);
extern void (*next_glUniform4dv)(GLint location, GLsizei count, const GLdouble* value);
extern void (*next_glUniformMatrix2dv)(GLint location, GLsizei count, GLboolean transpose, const GLdouble* value);
extern void (*next_glUniformMatrix2x3dv)(GLint location, GLsizei count, GLboolean transpose, const GLdouble* value);
extern void (*next_glUniformMatrix2x4dv)(GLint location, GLsizei count, GLboolean transpose, const GLdouble* value);
extern void (*next_glUniformMatrix3dv)(GLint location, GLsizei count, GLboolean transpose, const GLdouble* value);
extern void (*next_glUniformMatrix3x2dv)(GLint location, GLsizei count, GLboolean transpose, const GLdouble* value);
extern void (*next_glUniformMatrix3x4dv)(GLint location, GLsizei count, GLboolean transpose, const GLdouble* value);
extern void (*next_glUniformMatrix4dv)(GLint location, GLsizei count, GLboolean transpose, const GLdouble* value);
extern void (*next_glUniformMatrix4x2dv)(GLint location, GLsizei count, GLboolean transpose, const GLdouble* value);
extern void (*next_glUniformMatrix4x3dv)(GLint location, GLsizei count, GLboolean transpose, const GLdouble* value);
extern void (*next_glUniformSubroutinesuiv)(GLenum shadertype, GLsizei count, const GLuint* indices);


// GL_VERSION_4_1

extern void (*next_glActiveShaderProgram)(GLuint pipeline, GLuint program);
extern void (*next_glBindProgramPipeline)(GLuint pipeline);
extern void (*next_glClearDepthf)(GLfloat d);
extern GLuint (*next_glCreateShaderProgramv)(GLenum type, GLsizei count, const GLchar*const* strings);
extern void (*next_glDeleteProgramPipelines)(GLsizei n, const GLuint* pipelines);
extern void (*next_glDepthRangeArrayv)(GLuint first, GLsizei count, const GLdouble* v);
extern void (*next_glDepthRangeIndexed)(GLuint index, GLdouble n, GLdouble f);
extern void (*next_glDepthRangef)(GLfloat n, GLfloat f);
extern void (*next_glGenProgramPipelines)(GLsizei n, GLuint* pipelines);
extern void (*next_glGetDoublei_v)(GLenum target, GLuint index, GLdouble* data);
extern void (*next_glGetFloati_v)(GLenum target, GLuint index, GLfloat* data);
extern void (*next_glGetProgramBinary)(GLuint program, GLsizei bufSize, GLsizei* length, GLenum* binaryFormat, void * binary);
extern void (*next_glGetProgramPipelineInfoLog)(GLuint pipeline, GLsizei bufSize, GLsizei* length, GLchar* infoLog);
extern void (*next_glGetProgramPipelineiv)(GLuint pipeline, GLenum pname, GLint* params);
extern void (*next_glGetShaderPrecisionFormat)(GLenum shadertype, GLenum precisiontype, GLint* range, GLint* precision);
extern void (*next_glGetVertexAttribLdv)(GLuint index, GLenum pname, GLdouble* params);
extern GLboolean (*next_glIsProgramPipeline)(GLuint pipeline);
extern void (*next_glProgramBinary)(GLuint program, GLenum binaryFormat, const void * binary, GLsizei length);
extern void (*next_glProgramParameteri)(GLuint program, GLenum pname, GLint value);
extern void (*next_glProgramUniform1d)(GLuint program, GLint location, GLdouble v0);
extern void (*next_glProgramUniform1dv)(GLuint program, GLint location, GLsizei count, const GLdouble* value);
extern void (*next_glProgramUniform1f)(GLuint program, GLint location, GLfloat v0);
extern void (*next_glProgramUniform1fv)(GLuint program, GLint location, GLsizei count, const GLfloat* value);
extern void (*next_glProgramUniform1i)(GLuint program, GLint location, GLint v0);
extern void (*next_glProgramUniform1iv)(GLuint program, GLint location, GLsizei count, const GLint* value);
extern void (*next_glProgramUniform1ui)(GLuint program, GLint location, GLuint v0);
extern void (*next_glProgramUniform1uiv)(GLuint program, GLint location, GLsizei count, const GLuint* value);
extern void (*next_glProgramUniform2d)(GLuint program, GLint location, GLdouble v0, GLdouble v1);
extern void (*next_glProgramUniform2dv)(GLuint program, GLint location, GLsizei count, const GLdouble* value);
extern void (*next_glProgramUniform2f)(GLuint program, GLint location, GLfloat v0, GLfloat v1);
extern void (*next_glProgramUniform2fv)(GLuint program, GLint location, GLsizei count, const GLfloat* value);
extern void (*next_glProgramUniform2i)(GLuint program, GLint location, GLint v0, GLint v1);
extern void (*next_glProgramUniform2iv)(GLuint program, GLint location, GLsizei count, const GLint* value);
extern void (*next_glProgramUniform2ui)(GLuint program, GLint location, GLuint v0, GLuint v1);
extern void (*next_glProgramUniform2uiv)(GLuint program, GLint location, GLsizei count, const GLuint* value);
extern void (*next_glProgramUniform3d)(GLuint program, GLint location, GLdouble v0, GLdouble v1, GLdouble v2);
extern void (*next_glProgramUniform3dv)(GLuint program, GLint location, GLsizei count, const GLdouble* value);
extern void (*next_glProgramUniform3f)(GLuint program, GLint location, GLfloat v0, GLfloat v1, GLfloat v2);
extern void (*next_glProgramUniform3fv)(GLuint program, GLint location, GLsizei count, const GLfloat* value);
extern void (*next_glProgramUniform3i)(GLuint program, GLint location, GLint v0, GLint v1, GLint v2);
extern void (*next_glProgramUniform3iv)(GLuint program, GLint location, GLsizei count, const GLint* value);
extern void (*next_glProgramUniform3ui)(GLuint program, GLint location, GLuint v0, GLuint v1, GLuint v2);
extern void (*next_glProgramUniform3uiv)(GLuint program, GLint location, GLsizei count, const GLuint* value);
extern void (*next_glProgramUniform4d)(GLuint program, GLint location, GLdouble v0, GLdouble v1, GLdouble v2, GLdouble v3);
extern void (*next_glProgramUniform4dv)(GLuint program, GLint location, GLsizei count, const GLdouble* value);
extern void (*next_glProgramUniform4f)(GLuint program, GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3);
extern void (*next_glProgramUniform4fv)(GLuint program, GLint location, GLsizei count, const GLfloat* value);
extern void (*next_glProgramUniform4i)(GLuint program, GLint location, GLint v0, GLint v1, GLint v2, GLint v3);
extern void (*next_glProgramUniform4iv)(GLuint program, GLint location, GLsizei count, const GLint* value);
extern void (*next_glProgramUniform4ui)(GLuint program, GLint location, GLuint v0, GLuint v1, GLuint v2, GLuint v3);
extern void (*next_glProgramUniform4uiv)(GLuint program, GLint location, GLsizei count, const GLuint* value);
extern void (*next_glProgramUniformMatrix2dv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble* value);
extern void (*next_glProgramUniformMatrix2fv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
extern void (*next_glProgramUniformMatrix2x3dv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble* value);
extern void (*next_glProgramUniformMatrix2x3fv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
extern void (*next_glProgramUniformMatrix2x4dv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble* value);
extern void (*next_glProgramUniformMatrix2x4fv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
extern void (*next_glProgramUniformMatrix3dv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble* value);
extern void (*next_glProgramUniformMatrix3fv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
extern void (*next_glProgramUniformMatrix3x2dv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble* value);
extern void (*next_glProgramUniformMatrix3x2fv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
extern void (*next_glProgramUniformMatrix3x4dv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble* value);
extern void (*next_glProgramUniformMatrix3x4fv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
extern void (*next_glProgramUniformMatrix4dv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble* value);
extern void (*next_glProgramUniformMatrix4fv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
extern void (*next_glProgramUniformMatrix4x2dv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble* value);
extern void (*next_glProgramUniformMatrix4x2fv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
extern void (*next_glProgramUniformMatrix4x3dv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble* value);
extern void (*next_glProgramUniformMatrix4x3fv)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
extern void (*next_glReleaseShaderCompiler)();
extern void (*next_glScissorArrayv)(GLuint first, GLsizei count, const GLint* v);
extern void (*next_glScissorIndexed)(GLuint index, GLint left, GLint bottom, GLsizei width, GLsizei height);
extern void (*next_glScissorIndexedv)(GLuint index, const GLint* v);
extern void (*next_glShaderBinary)(GLsizei count, const GLuint* shaders, GLenum binaryformat, const void * binary, GLsizei length);
extern void (*next_glUseProgramStages)(GLuint pipeline, GLbitfield stages, GLuint program);
extern void (*next_glValidateProgramPipeline)(GLuint pipeline);
extern void (*next_glVertexAttribL1d)(GLuint index, GLdouble x);
extern void (*next_glVertexAttribL1dv)(GLuint index, const GLdouble* v);
extern void (*next_glVertexAttribL2d)(GLuint index, GLdouble x, GLdouble y);
extern void (*next_glVertexAttribL2dv)(GLuint index, const GLdouble* v);
extern void (*next_glVertexAttribL3d)(GLuint index, GLdouble x, GLdouble y, GLdouble z);
extern void (*next_glVertexAttribL3dv)(GLuint index, const GLdouble* v);
extern void (*next_glVertexAttribL4d)(GLuint index, GLdouble x, GLdouble y, GLdouble z, GLdouble w);
extern void (*next_glVertexAttribL4dv)(GLuint index, const GLdouble* v);
extern void (*next_glVertexAttribLPointer)(GLuint index, GLint size, GLenum type, GLsizei stride, const void * pointer);
extern void (*next_glViewportArrayv)(GLuint first, GLsizei count, const GLfloat* v);
extern void (*next_glViewportIndexedf)(GLuint index, GLfloat x, GLfloat y, GLfloat w, GLfloat h);
extern void (*next_glViewportIndexedfv)(GLuint index, const GLfloat* v);


// GL_VERSION_4_2

extern void (*next_glBindImageTexture)(GLuint unit, GLuint texture, GLint level, GLboolean layered, GLint layer, GLenum access, GLenum format);
extern void (*next_glDrawArraysInstancedBaseInstance)(GLenum mode, GLint first, GLsizei count, GLsizei instancecount, GLuint baseinstance);
extern void (*next_glDrawElementsInstancedBaseInstance)(GLenum mode, GLsizei count, GLenum type, const void * indices, GLsizei instancecount, GLuint baseinstance);
extern void (*next_glDrawElementsInstancedBaseVertexBaseInstance)(GLenum mode, GLsizei count, GLenum type, const void * indices, GLsizei instancecount, GLint basevertex, GLuint baseinstance);
extern void (*next_glDrawTransformFeedbackInstanced)(GLenum mode, GLuint id, GLsizei instancecount);
extern void (*next_glDrawTransformFeedbackStreamInstanced)(GLenum mode, GLuint id, GLuint stream, GLsizei instancecount);
extern void (*next_glGetActiveAtomicCounterBufferiv)(GLuint program, GLuint bufferIndex, GLenum pname, GLint* params);
extern void (*next_glGetInternalformativ)(GLenum target, GLenum internalformat, GLenum pname, GLsizei bufSize, GLint* params);
extern void (*next_glMemoryBarrier)(GLbitfield barriers);
extern void (*next_glTexStorage1D)(GLenum target, GLsizei levels, GLenum internalformat, GLsizei width);
extern void (*next_glTexStorage2D)(GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height);
extern void (*next_glTexStorage3D)(GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth);


// GL_VERSION_4_3

extern void (*next_glBindVertexBuffer)(GLuint bindingindex, GLuint buffer, GLintptr offset, GLsizei stride);
extern void (*next_glClearBufferData)(GLenum target, GLenum internalformat, GLenum format, GLenum type, const void * data);
extern void (*next_glClearBufferSubData)(GLenum target, GLenum internalformat, GLintptr offset, GLsizeiptr size, GLenum format, GLenum type, const void * data);
extern void (*next_glCopyImageSubData)(GLuint srcName, GLenum srcTarget, GLint srcLevel, GLint srcX, GLint srcY, GLint srcZ, GLuint dstName, GLenum dstTarget, GLint dstLevel, GLint dstX, GLint dstY, GLint dstZ, GLsizei srcWidth, GLsizei srcHeight, GLsizei srcDepth);
extern void (*next_glDebugMessageCallback)(GLDEBUGPROC callback, const void * userParam);
extern void (*next_glDebugMessageControl)(GLenum source, GLenum type, GLenum severity, GLsizei count, const GLuint* ids, GLboolean enabled);
extern void (*next_glDebugMessageInsert)(GLenum source, GLenum type, GLuint id, GLenum severity, GLsizei length, const GLchar* buf);
extern void (*next_glDispatchCompute)(GLuint num_groups_x, GLuint num_groups_y, GLuint num_groups_z);
extern void (*next_glDispatchComputeIndirect)(GLintptr indirect);
extern void (*next_glFramebufferParameteri)(GLenum target, GLenum pname, GLint param);
extern GLuint (*next_glGetDebugMessageLog)(GLuint count, GLsizei bufSize, GLenum* sources, GLenum* types, GLuint* ids, GLenum* severities, GLsizei* lengths, GLchar* messageLog);
extern void (*next_glGetFramebufferParameteriv)(GLenum target, GLenum pname, GLint* params);
extern void (*next_glGetInternalformati64v)(GLenum target, GLenum internalformat, GLenum pname, GLsizei bufSize, GLint64* params);
extern void (*next_glGetObjectLabel)(GLenum identifier, GLuint name, GLsizei bufSize, GLsizei* length, GLchar* label);
extern void (*next_glGetObjectPtrLabel)(const void * ptr, GLsizei bufSize, GLsizei* length, GLchar* label);
extern void (*next_glGetProgramInterfaceiv)(GLuint program, GLenum programInterface, GLenum pname, GLint* params);
extern GLuint (*next_glGetProgramResourceIndex)(GLuint program, GLenum programInterface, const GLchar* name);
extern GLint (*next_glGetProgramResourceLocation)(GLuint program, GLenum programInterface, const GLchar* name);
extern GLint (*next_glGetProgramResourceLocationIndex)(GLuint program, GLenum programInterface, const GLchar* name);
extern void (*next_glGetProgramResourceName)(GLuint program, GLenum programInterface, GLuint index, GLsizei bufSize, GLsizei* length, GLchar* name);
extern void (*next_glGetProgramResourceiv)(GLuint program, GLenum programInterface, GLuint index, GLsizei propCount, const GLenum* props, GLsizei bufSize, GLsizei* length, GLint* params);
extern void (*next_glInvalidateBufferData)(GLuint buffer);
extern void (*next_glInvalidateBufferSubData)(GLuint buffer, GLintptr offset, GLsizeiptr length);
extern void (*next_glInvalidateFramebuffer)(GLenum target, GLsizei numAttachments, const GLenum* attachments);
extern void (*next_glInvalidateSubFramebuffer)(GLenum target, GLsizei numAttachments, const GLenum* attachments, GLint x, GLint y, GLsizei width, GLsizei height);
extern void (*next_glInvalidateTexImage)(GLuint texture, GLint level);
extern void (*next_glInvalidateTexSubImage)(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth);
extern void (*next_glMultiDrawArraysIndirect)(GLenum mode, const void * indirect, GLsizei drawcount, GLsizei stride);
extern void (*next_glMultiDrawElementsIndirect)(GLenum mode, GLenum type, const void * indirect, GLsizei drawcount, GLsizei stride);
extern void (*next_glObjectLabel)(GLenum identifier, GLuint name, GLsizei length, const GLchar* label);
extern void (*next_glObjectPtrLabel)(const void * ptr, GLsizei length, const GLchar* label);
extern void (*next_glPopDebugGroup)();
extern void (*next_glPushDebugGroup)(GLenum source, GLuint id, GLsizei length, const GLchar* message);
extern void (*next_glShaderStorageBlockBinding)(GLuint program, GLuint storageBlockIndex, GLuint storageBlockBinding);
extern void (*next_glTexBufferRange)(GLenum target, GLenum internalformat, GLuint buffer, GLintptr offset, GLsizeiptr size);
extern void (*next_glTexStorage2DMultisample)(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLboolean fixedsamplelocations);
extern void (*next_glTexStorage3DMultisample)(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLboolean fixedsamplelocations);
extern void (*next_glTextureView)(GLuint texture, GLenum target, GLuint origtexture, GLenum internalformat, GLuint minlevel, GLuint numlevels, GLuint minlayer, GLuint numlayers);
extern void (*next_glVertexAttribBinding)(GLuint attribindex, GLuint bindingindex);
extern void (*next_glVertexAttribFormat)(GLuint attribindex, GLint size, GLenum type, GLboolean normalized, GLuint relativeoffset);
extern void (*next_glVertexAttribIFormat)(GLuint attribindex, GLint size, GLenum type, GLuint relativeoffset);
extern void (*next_glVertexAttribLFormat)(GLuint attribindex, GLint size, GLenum type, GLuint relativeoffset);
extern void (*next_glVertexBindingDivisor)(GLuint bindingindex, GLuint divisor);


// GL_VERSION_4_4

extern void (*next_glBindBuffersBase)(GLenum target, GLuint first, GLsizei count, const GLuint* buffers);
extern void (*next_glBindBuffersRange)(GLenum target, GLuint first, GLsizei count, const GLuint* buffers, const GLintptr* offsets, const GLsizeiptr* sizes);
extern void (*next_glBindImageTextures)(GLuint first, GLsizei count, const GLuint* textures);
extern void (*next_glBindSamplers)(GLuint first, GLsizei count, const GLuint* samplers);
extern void (*next_glBindTextures)(GLuint first, GLsizei count, const GLuint* textures);
extern void (*next_glBindVertexBuffers)(GLuint first, GLsizei count, const GLuint* buffers, const GLintptr* offsets, const GLsizei* strides);
extern void (*next_glBufferStorage)(GLenum target, GLsizeiptr size, const void * data, GLbitfield flags);
extern void (*next_glClearTexImage)(GLuint texture, GLint level, GLenum format, GLenum type, const void * data);
extern void (*next_glClearTexSubImage)(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const void * data);


// GL_VERSION_4_5

extern void (*next_glBindTextureUnit)(GLuint unit, GLuint texture);
extern void (*next_glBlitNamedFramebuffer)(GLuint readFramebuffer, GLuint drawFramebuffer, GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter);
extern GLenum (*next_glCheckNamedFramebufferStatus)(GLuint framebuffer, GLenum target);
extern void (*next_glClearNamedBufferData)(GLuint buffer, GLenum internalformat, GLenum format, GLenum type, const void * data);
extern void (*next_glClearNamedBufferSubData)(GLuint buffer, GLenum internalformat, GLintptr offset, GLsizeiptr size, GLenum format, GLenum type, const void * data);
extern void (*next_glClearNamedFramebufferfi)(GLuint framebuffer, GLenum buffer, GLint drawbuffer, GLfloat depth, GLint stencil);
extern void (*next_glClearNamedFramebufferfv)(GLuint framebuffer, GLenum buffer, GLint drawbuffer, const GLfloat* value);
extern void (*next_glClearNamedFramebufferiv)(GLuint framebuffer, GLenum buffer, GLint drawbuffer, const GLint* value);
extern void (*next_glClearNamedFramebufferuiv)(GLuint framebuffer, GLenum buffer, GLint drawbuffer, const GLuint* value);
extern void (*next_glClipControl)(GLenum origin, GLenum depth);
extern void (*next_glCompressedTextureSubImage1D)(GLuint texture, GLint level, GLint xoffset, GLsizei width, GLenum format, GLsizei imageSize, const void * data);
extern void (*next_glCompressedTextureSubImage2D)(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const void * data);
extern void (*next_glCompressedTextureSubImage3D)(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const void * data);
extern void (*next_glCopyNamedBufferSubData)(GLuint readBuffer, GLuint writeBuffer, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size);
extern void (*next_glCopyTextureSubImage1D)(GLuint texture, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width);
extern void (*next_glCopyTextureSubImage2D)(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height);
extern void (*next_glCopyTextureSubImage3D)(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height);
extern void (*next_glCreateBuffers)(GLsizei n, GLuint* buffers);
extern void (*next_glCreateFramebuffers)(GLsizei n, GLuint* framebuffers);
extern void (*next_glCreateProgramPipelines)(GLsizei n, GLuint* pipelines);
extern void (*next_glCreateQueries)(GLenum target, GLsizei n, GLuint* ids);
extern void (*next_glCreateRenderbuffers)(GLsizei n, GLuint* renderbuffers);
extern void (*next_glCreateSamplers)(GLsizei n, GLuint* samplers);
extern void (*next_glCreateTextures)(GLenum target, GLsizei n, GLuint* textures);
extern void (*next_glCreateTransformFeedbacks)(GLsizei n, GLuint* ids);
extern void (*next_glCreateVertexArrays)(GLsizei n, GLuint* arrays);
extern void (*next_glDisableVertexArrayAttrib)(GLuint vaobj, GLuint index);
extern void (*next_glEnableVertexArrayAttrib)(GLuint vaobj, GLuint index);
extern void (*next_glFlushMappedNamedBufferRange)(GLuint buffer, GLintptr offset, GLsizeiptr length);
extern void (*next_glGenerateTextureMipmap)(GLuint texture);
extern void (*next_glGetCompressedTextureImage)(GLuint texture, GLint level, GLsizei bufSize, void * pixels);
extern void (*next_glGetCompressedTextureSubImage)(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLsizei bufSize, void * pixels);
extern GLenum (*next_glGetGraphicsResetStatus)();
extern void (*next_glGetNamedBufferParameteri64v)(GLuint buffer, GLenum pname, GLint64* params);
extern void (*next_glGetNamedBufferParameteriv)(GLuint buffer, GLenum pname, GLint* params);
extern void (*next_glGetNamedBufferPointerv)(GLuint buffer, GLenum pname, void ** params);
extern void (*next_glGetNamedBufferSubData)(GLuint buffer, GLintptr offset, GLsizeiptr size, void * data);
extern void (*next_glGetNamedFramebufferAttachmentParameteriv)(GLuint framebuffer, GLenum attachment, GLenum pname, GLint* params);
extern void (*next_glGetNamedFramebufferParameteriv)(GLuint framebuffer, GLenum pname, GLint* param);
extern void (*next_glGetNamedRenderbufferParameteriv)(GLuint renderbuffer, GLenum pname, GLint* params);
extern void (*next_glGetQueryBufferObjecti64v)(GLuint id, GLuint buffer, GLenum pname, GLintptr offset);
extern void (*next_glGetQueryBufferObjectiv)(GLuint id, GLuint buffer, GLenum pname, GLintptr offset);
extern void (*next_glGetQueryBufferObjectui64v)(GLuint id, GLuint buffer, GLenum pname, GLintptr offset);
extern void (*next_glGetQueryBufferObjectuiv)(GLuint id, GLuint buffer, GLenum pname, GLintptr offset);
extern void (*next_glGetTextureImage)(GLuint texture, GLint level, GLenum format, GLenum type, GLsizei bufSize, void * pixels);
extern void (*next_glGetTextureLevelParameterfv)(GLuint texture, GLint level, GLenum pname, GLfloat* params);
extern void (*next_glGetTextureLevelParameteriv)(GLuint texture, GLint level, GLenum pname, GLint* params);
extern void (*next_glGetTextureParameterIiv)(GLuint texture, GLenum pname, GLint* params);
extern void (*next_glGetTextureParameterIuiv)(GLuint texture, GLenum pname, GLuint* params);
extern void (*next_glGetTextureParameterfv)(GLuint texture, GLenum pname, GLfloat* params);
extern void (*next_glGetTextureParameteriv)(GLuint texture, GLenum pname, GLint* params);
extern void (*next_glGetTextureSubImage)(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, GLsizei bufSize, void * pixels);
extern void (*next_glGetTransformFeedbacki64_v)(GLuint xfb, GLenum pname, GLuint index, GLint64* param);
extern void (*next_glGetTransformFeedbacki_v)(GLuint xfb, GLenum pname, GLuint index, GLint* param);
extern void (*next_glGetTransformFeedbackiv)(GLuint xfb, GLenum pname, GLint* param);
extern void (*next_glGetVertexArrayIndexed64iv)(GLuint vaobj, GLuint index, GLenum pname, GLint64* param);
extern void (*next_glGetVertexArrayIndexediv)(GLuint vaobj, GLuint index, GLenum pname, GLint* param);
extern void (*next_glGetVertexArrayiv)(GLuint vaobj, GLenum pname, GLint* param);
extern void (*next_glGetnColorTable)(GLenum target, GLenum format, GLenum type, GLsizei bufSize, void * table);
extern void (*next_glGetnCompressedTexImage)(GLenum target, GLint lod, GLsizei bufSize, void * pixels);
extern void (*next_glGetnConvolutionFilter)(GLenum target, GLenum format, GLenum type, GLsizei bufSize, void * image);
extern void (*next_glGetnHistogram)(GLenum target, GLboolean reset, GLenum format, GLenum type, GLsizei bufSize, void * values);
extern void (*next_glGetnMapdv)(GLenum target, GLenum query, GLsizei bufSize, GLdouble* v);
extern void (*next_glGetnMapfv)(GLenum target, GLenum query, GLsizei bufSize, GLfloat* v);
extern void (*next_glGetnMapiv)(GLenum target, GLenum query, GLsizei bufSize, GLint* v);
extern void (*next_glGetnMinmax)(GLenum target, GLboolean reset, GLenum format, GLenum type, GLsizei bufSize, void * values);
extern void (*next_glGetnPixelMapfv)(GLenum map, GLsizei bufSize, GLfloat* values);
extern void (*next_glGetnPixelMapuiv)(GLenum map, GLsizei bufSize, GLuint* values);
extern void (*next_glGetnPixelMapusv)(GLenum map, GLsizei bufSize, GLushort* values);
extern void (*next_glGetnPolygonStipple)(GLsizei bufSize, GLubyte* pattern);
extern void (*next_glGetnSeparableFilter)(GLenum target, GLenum format, GLenum type, GLsizei rowBufSize, void * row, GLsizei columnBufSize, void * column, void * span);
extern void (*next_glGetnTexImage)(GLenum target, GLint level, GLenum format, GLenum type, GLsizei bufSize, void * pixels);
extern void (*next_glGetnUniformdv)(GLuint program, GLint location, GLsizei bufSize, GLdouble* params);
extern void (*next_glGetnUniformfv)(GLuint program, GLint location, GLsizei bufSize, GLfloat* params);
extern void (*next_glGetnUniformiv)(GLuint program, GLint location, GLsizei bufSize, GLint* params);
extern void (*next_glGetnUniformuiv)(GLuint program, GLint location, GLsizei bufSize, GLuint* params);
extern void (*next_glInvalidateNamedFramebufferData)(GLuint framebuffer, GLsizei numAttachments, const GLenum* attachments);
extern void (*next_glInvalidateNamedFramebufferSubData)(GLuint framebuffer, GLsizei numAttachments, const GLenum* attachments, GLint x, GLint y, GLsizei width, GLsizei height);
extern void * (*next_glMapNamedBuffer)(GLuint buffer, GLenum access);
extern void * (*next_glMapNamedBufferRange)(GLuint buffer, GLintptr offset, GLsizeiptr length, GLbitfield access);
extern void (*next_glMemoryBarrierByRegion)(GLbitfield barriers);
extern void (*next_glNamedBufferData)(GLuint buffer, GLsizeiptr size, const void * data, GLenum usage);
extern void (*next_glNamedBufferStorage)(GLuint buffer, GLsizeiptr size, const void * data, GLbitfield flags);
extern void (*next_glNamedBufferSubData)(GLuint buffer, GLintptr offset, GLsizeiptr size, const void * data);
extern void (*next_glNamedFramebufferDrawBuffer)(GLuint framebuffer, GLenum buf);
extern void (*next_glNamedFramebufferDrawBuffers)(GLuint framebuffer, GLsizei n, const GLenum* bufs);
extern void (*next_glNamedFramebufferParameteri)(GLuint framebuffer, GLenum pname, GLint param);
extern void (*next_glNamedFramebufferReadBuffer)(GLuint framebuffer, GLenum src);
extern void (*next_glNamedFramebufferRenderbuffer)(GLuint framebuffer, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer);
extern void (*next_glNamedFramebufferTexture)(GLuint framebuffer, GLenum attachment, GLuint texture, GLint level);
extern void (*next_glNamedFramebufferTextureLayer)(GLuint framebuffer, GLenum attachment, GLuint texture, GLint level, GLint layer);
extern void (*next_glNamedRenderbufferStorage)(GLuint renderbuffer, GLenum internalformat, GLsizei width, GLsizei height);
extern void (*next_glNamedRenderbufferStorageMultisample)(GLuint renderbuffer, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height);
extern void (*next_glReadnPixels)(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLsizei bufSize, void * data);
extern void (*next_glTextureBarrier)();
extern void (*next_glTextureBuffer)(GLuint texture, GLenum internalformat, GLuint buffer);
extern void (*next_glTextureBufferRange)(GLuint texture, GLenum internalformat, GLuint buffer, GLintptr offset, GLsizeiptr size);
extern void (*next_glTextureParameterIiv)(GLuint texture, GLenum pname, const GLint* params);
extern void (*next_glTextureParameterIuiv)(GLuint texture, GLenum pname, const GLuint* params);
extern void (*next_glTextureParameterf)(GLuint texture, GLenum pname, GLfloat param);
extern void (*next_glTextureParameterfv)(GLuint texture, GLenum pname, const GLfloat* param);
extern void (*next_glTextureParameteri)(GLuint texture, GLenum pname, GLint param);
extern void (*next_glTextureParameteriv)(GLuint texture, GLenum pname, const GLint* param);
extern void (*next_glTextureStorage1D)(GLuint texture, GLsizei levels, GLenum internalformat, GLsizei width);
extern void (*next_glTextureStorage2D)(GLuint texture, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height);
extern void (*next_glTextureStorage2DMultisample)(GLuint texture, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLboolean fixedsamplelocations);
extern void (*next_glTextureStorage3D)(GLuint texture, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth);
extern void (*next_glTextureStorage3DMultisample)(GLuint texture, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLboolean fixedsamplelocations);
extern void (*next_glTextureSubImage1D)(GLuint texture, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const void * pixels);
extern void (*next_glTextureSubImage2D)(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const void * pixels);
extern void (*next_glTextureSubImage3D)(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const void * pixels);
extern void (*next_glTransformFeedbackBufferBase)(GLuint xfb, GLuint index, GLuint buffer);
extern void (*next_glTransformFeedbackBufferRange)(GLuint xfb, GLuint index, GLuint buffer, GLintptr offset, GLsizeiptr size);
extern GLboolean (*next_glUnmapNamedBuffer)(GLuint buffer);
extern void (*next_glVertexArrayAttribBinding)(GLuint vaobj, GLuint attribindex, GLuint bindingindex);
extern void (*next_glVertexArrayAttribFormat)(GLuint vaobj, GLuint attribindex, GLint size, GLenum type, GLboolean normalized, GLuint relativeoffset);
extern void (*next_glVertexArrayAttribIFormat)(GLuint vaobj, GLuint attribindex, GLint size, GLenum type, GLuint relativeoffset);
extern void (*next_glVertexArrayAttribLFormat)(GLuint vaobj, GLuint attribindex, GLint size, GLenum type, GLuint relativeoffset);
extern void (*next_glVertexArrayBindingDivisor)(GLuint vaobj, GLuint bindingindex, GLuint divisor);
extern void (*next_glVertexArrayElementBuffer)(GLuint vaobj, GLuint buffer);
extern void (*next_glVertexArrayVertexBuffer)(GLuint vaobj, GLuint bindingindex, GLuint buffer, GLintptr offset, GLsizei stride);
extern void (*next_glVertexArrayVertexBuffers)(GLuint vaobj, GLuint first, GLsizei count, const GLuint* buffers, const GLintptr* offsets, const GLsizei* strides);


// GLX

extern XVisualInfo * (*next_glXChooseVisual)(Display * dpy, GLint screen, GLint * attriblist);
extern void (*next_glXDestroyContext)(Display * dpy, GLXContext ctx);
extern Bool (*next_glXMakeCurrent)(Display * dpy, GLXDrawable drawable, GLXContext ctx);
extern void (*next_glXSwapBuffers)(Display * dpy, GLXDrawable drawable);


// MPI

extern void (*next_MPI_Finalize)();


//Other

static void* (*next_dlsym)(void *handle, const char *name) = NULL;